### ISSUE TITLE
/afk broadcast support.

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/TestIssueUploader#300]
CMDBOOK-2143 - Reported by Senan.Kelly on 2012-11-23 18:36:24 UTC

Please; can we have support to broadcast ''(with displayName(s))'' when I player uses ''/afk''? 
config ideas:

```yaml|title=config.yml
    messaging:
        console-say-format: '`r<Server> %s'
        broadcast-format: '`r<Broadcast>`w %s'
        pm-color: GRAY
        pm-text-color: RESET
        twitter-style: true
        broadcast-afk: true
```
This would be really useful so that players don't need to use ''/whois'' or anything to find out why they're not responding to messages.
